# -*- coding: utf-8 -*-
"""assignment-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SRY3aVGl1A8vfmIVtE6U8FcmvP_Uptld
"""

def number(odd_or_even) :
  if odd_or_even %2== 0:
    print(str(odd_or_even) + " is even")
  else:
    print(str(odd_or_even) + " is odd")



number(1)
number(2)
number(9999)